class MyStruct:
     
     #QPIRI_Format
    QPIRI = {
         'Grid rating voltage': 000.0,
         'Grid rating current': 00.0,
         'AC output rating voltage': 000.0,
         'AC output rating frequency': 00.0,
         'AC output rating current': 00.0,
         'AC output rating apparent power': 0000,
         'AC output rating active power': 0000,
         'Battery rating voltage': 00.0,
         'Battery re-charge voltage': 00.0,
         'Battery under voltage': 00.0,
         'Battery bulk voltage': 00.0,
         'Battery float voltage': 00.0,
         'Battery type': 0,
         'Current max AC charging current': 00,
         'Current max charging current': 000,
         'Input voltage range': 0,
         'Output source priority': 0,
         'Charger source priority': 0,
         'Parallel max number': 0,
         'Machine type': 00,
         'Topology': 0,
         'Output mode': 0,
         'Battery re-discharge voltage': 00.0,
         'PV OK condition for parallel': 0,
         'PV power balance': 0,
         'Max. charging time at C.V stage': 000,
         'Operation Logic': 0
    }
    

    #QPIGS_Format
    QPIGS = {
         'Grid voltage': 000.0,
         'Grid frequency': 00.0,
         'AC output voltage': 000.0,
         'AC output frequency': 00.0,
         'AC output apparent power': 0000,
         'AC output active power': 0000,
         'Output load percent': 000,
         'BUS voltage': 000,
         'Battery voltage ': 00.00,
         'Battery charging current': 000,
         'Battery capacity': 000,
         'Inverter heat sink temperature': 0000,
         'PV Input current for battery': 0000,
         'PV Input voltage 1 ': 000.0,
         'Battery voltage from SCC': 00.00,
         'Battery discharge current': 0000,
         'Inverter status 1': 00000000,
         'Battery voltage offset for fans on': 00,
         'EEPROM version': 00,
         'PV Charging power': 00000,
         'Inverter status 2': 000
    }

    #QPGSn_Format
    QPGSn = {
        'The parallel num whether exist': 0,
        'Serial number': 00000000000000,
        'Work mode': '',
        'Fault code': 00,
        'Grid voltage': 000.0,
        'Grid frequency': 00.00,
        'AC output voltage': 000.0,
        'AC output frequency': 00.00,
        'AC output apparent power': 0000,
        'AC output active power': 0000,
        'Load percentage': 000,
        'Battery voltage': 00.0,
        'Battery charging current': 000,
        'Battery capacity': 000,
        'PV Input Voltage': 000.0,
        'Total charging current ': 000,
        'Total AC output apparent power': 00000,
        'Total output active power': 00000,
        'Total AC output percentage': 000,
        'Inverter Status': 00000000,
        'Output mode': 0,
        'Charger source priority': 0,
        'Max charger current': 000,
        'Max charger range': 000,
        'Max AC charger current ': 00,
        'PV input current for battery': 00,
        'Battery discharge current': 000
    }

    #QDI_Format
    QDI = {
        'AC output voltage': 000.0,
        'AC output frequency': 00.0,
        'Max AC charging current': 0000,
        'Battery Under voltage': 00.0,
        'Charging float voltage': 00.0,
        'Charging bulk voltage': 00.0,
        'Battery default re-charge voltage': 00.0,
        'Max charging current': 00,
        'AC input voltage range': 0,
        'Output source priority': 0,
        'Charger source priority': 0,
        'Battery type': 0,
        'Enable/disable silence buzzer or open buzzer': 0,
        'Enable/Disable power saving': 0,
        'Enable/Disable overload restart': 0,
        'Enable/Disable over temperature restart': 0,
        'Enable/Disable LCD backlight on': 0,
        'Enable/Disable alarm on when primary source interrupt': 0,
        'Enable/Disable fault code record': 0,
        'Overload bypass': 0,
        'Enable/Disable LCD display escape to default page after 1min timeout': 0,
        'Output mode': 0,
        'Battery re-discharge voltage': 00.0,
        'PV OK condition for parallel': 0,
        'PV power balance': 0,
        'Max. charging time at C.V stage': 000,
        'Operation logic': 0
    }
