class MyStruct:
    QPIRI = {
         'Grid rating voltage': 000.0,
         'Grid rating current': 00.0,
         'AC output rating voltage': 000.0,
         'AC output rating frequency': 00.0,
         'AC output rating current': 00.0,
         'AC output rating apparent power': 0000,
         'AC output rating active power': 0000,
         'Battery rating voltage': 00.0,
         'Battery re-charge voltage': 00.0,
         'Battery under voltage': 00.0,
         'Battery bulk voltage': 00.0,
         'Battery float voltage': 00.0,
         'Battery type': 0,
         'Current max AC charging current': 00,
         'Current max charging current': 000,
         'Input voltage range': 0,
         'Output source priority': 0,
         'Charger source priority': 0,
         'Parallel max number': 0,
         'Machine type': 00,
         'Topology': 0,
         'Output mode': 0,
         'Battery re-discharge voltage': 00.0,
         'PV OK condition for parallel': 0,
         'PV power balance': 0,
         'Max. charging time at C.V stage': 000,
         'Operation Logic': 0
    }  
